/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package isdbms;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Ravi
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Password = new javax.swing.JTextField();
        kButton1 = new keeptoo.KButton();
        kButton2 = new keeptoo.KButton();
        jLabel4 = new javax.swing.JLabel();
        USER2 = new javax.swing.JTextField();
        USER3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        USER4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        USER5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        USER6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        USER1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        USER7 = new javax.swing.JTextField();
        PASSWORD = new javax.swing.JLabel();
        kButton3 = new keeptoo.KButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 100, 740, 0));
        setUndecorated(true);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NEW USER REGISTRATION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 350, 40));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USER ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 160, 30));

        Username.setBackground(new Color(0,0,0,0));
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 280, 30));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PASSWORD");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 160, 30));

        Password.setBackground(new Color(0,0,0,0));
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        Password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 280, 30));

        kButton1.setText("LOGIN");
        kButton1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        kButton1.setkFillButton(false);
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, -1));

        kButton2.setText("EXIT");
        kButton2.setkBorderRadius(70);
        kButton2.setkFillButton(false);
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 50, 30));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GENDER");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 160, 30));

        USER2.setBackground(new Color(0,0,0,0));
        USER2.setForeground(new java.awt.Color(255, 255, 255));
        USER2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(USER2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 280, 30));

        USER3.setBackground(new Color(0,0,0,0));
        USER3.setForeground(new java.awt.Color(255, 255, 255));
        USER3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(USER3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 280, 30));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("E-MAIL");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 160, 30));

        USER4.setBackground(new Color(0,0,0,0));
        USER4.setForeground(new java.awt.Color(255, 255, 255));
        USER4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(USER4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 280, 30));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NUMBER");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 160, 30));

        USER5.setBackground(new Color(0,0,0,0));
        USER5.setForeground(new java.awt.Color(255, 255, 255));
        USER5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        USER5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USER5ActionPerformed(evt);
            }
        });
        jPanel1.add(USER5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 280, 30));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ADDRESS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, 160, 30));

        USER6.setBackground(new Color(0,0,0,0));
        USER6.setForeground(new java.awt.Color(255, 255, 255));
        USER6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(USER6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 280, 30));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("USER ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 160, 30));

        USER1.setBackground(new Color(0,0,0,0));
        USER1.setForeground(new java.awt.Color(255, 255, 255));
        USER1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(USER1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 280, 30));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("FULL NAME");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 160, 30));

        USER7.setBackground(new Color(0,0,0,0));
        USER7.setForeground(new java.awt.Color(255, 255, 255));
        USER7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        USER7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USER7ActionPerformed(evt);
            }
        });
        jPanel1.add(USER7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 590, 280, 30));

        PASSWORD.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        PASSWORD.setForeground(new java.awt.Color(255, 255, 255));
        PASSWORD.setText("PASSWORD");
        jPanel1.add(PASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, 160, 30));

        kButton3.setText("SUBMIT");
        kButton3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        kButton3.setkFillButton(false);
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 640, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("USER LOGIN");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 200, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
         try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/isdbms","root","");
            String sql = "Select * from userregistration where UserID=?  and Password=?";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1, Username.getText());
            pst.setString(2, Password.getText());
            ResultSet rs=pst.executeQuery();
            if(rs.next()) {
                JOptionPane.showMessageDialog(null, "WELCOME TO INDIAN SPACE DATEBASE MANAGEMENT SYSTEM  !!!!!!!");
                dispose();
                new Home().setVisible(true);
            }
            else {
                JOptionPane.showMessageDialog(null, "INVALID USER !!! PLEASE CHECK YOUR USERNAME AND PASSWORD");
            }
            con.close();
            
        }catch(Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_kButton2ActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void USER5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USER5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USER5ActionPerformed

    private void USER7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USER7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USER7ActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/isdbms","root","");
            String sql = "INSERT INTO `userregistration`(`FullName`, `Gender`, `E-Mail`, `Number`, `Address`, `UserID`, `Password`) VALUES (?,?,?,?,?,?,?)";

            PreparedStatement pst=con.prepareStatement(sql); 
            
			pst.setString(1, USER1.getText());
			pst.setString(2, USER2.getText());
			pst.setString(3, USER3.getText());
			pst.setString(4, USER4.getText());
			pst.setString(5, USER5.getText());
			pst.setString(6, USER6.getText());
                        pst.setString(7, USER7.getText());
            if(pst.executeUpdate()!=0){
                JOptionPane.showMessageDialog(null, "New User Registered Successfully!!!");
                
            }
            else{
                    JOptionPane.showMessageDialog(null, "Something Is Wrong!!!");
                    }
            con.close();
            
        }catch(Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_kButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PASSWORD;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField USER1;
    private javax.swing.JTextField USER2;
    private javax.swing.JTextField USER3;
    private javax.swing.JTextField USER4;
    private javax.swing.JTextField USER5;
    private javax.swing.JTextField USER6;
    private javax.swing.JTextField USER7;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KButton kButton1;
    private keeptoo.KButton kButton2;
    private keeptoo.KButton kButton3;
    // End of variables declaration//GEN-END:variables
}
